### ISSUE TITLE
how do i run it in kali linux

### ISSUE THREAD

**Issue by LilCyro** [NewEraCracker/LOIC#103]
how do i run it in kali i have cloned the repostiory and installed it using     bash loic.sh run but i get this error

/usr/bin/git
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package monodevelop
loic.sh: line 80: xbuild: command not found
/usr/bin/mono
cp: cannot stat './src/app.config': No such file or directory
Cannot open assembly 'src/bin/Debug/LOIC.exe': No such file or directory.

**Comment by NewEraCracker** [comment]
Clearly you are missing the monodevelop package and xbuild tool.

If you did a simple search in issues you'd find: https://github.com/NewEraCracker/LOIC/issues/92

And I also mention this in the script: https://github.com/NewEraCracker/LOIC/blob/master/loic-net4.5.sh#L13

**Comment by samuraix12** [comment]
bro me to but i have the monodevelop package but still cant open it please help with
