### ISSUE TITLE
How to change threads in the new version

### ISSUE THREAD

**Issue by jiuyi666** [NewEraCracker/LOIC#107]
The new version of the thread is limited to less than 100. I want to change it to threads 1000-200. How do I modify it

**Comment by jiuyi666** [comment]
Please help me

**Comment by NewEraCracker** [comment]
Thank you for reaching out regarding the thread limit in the new version. While your interest is appreciated, we regret to inform you that we are unable to assist with modifying the thread limit as per your request.

The request to change the thread limit is considered out of scope for our project. The current thread limit has been intentionally set to ensure optimal performance and stability. Increasing the thread limit to the range you specified could potentially impact the performance and resource consumption of the application. We believe that the current thread limit strikes a balance between functionality and system efficiency.

Thank you for your understanding.

Best regards,
