### ISSUE TITLE
cant even run it

### ISSUE THREAD

**Issue by hsheheheheheueuywg** [NewEraCracker/LOIC#110]

**Comment by hsheheheheheueuywg** [comment]
![Screenshot 2023-08-14 183359](https://github.com/NewEraCracker/LOIC/assets/79226636/fc656165-30d9-4835-b1db-bee5c4ec45e


what is the file to open the loic

**Comment by hsheheheheheueuywg** [comment]
what file to open the loic

**Comment by NewEraCracker** [comment]
Please refrain from opening issues answered before, especially with little to no detail:

Use search: https://github.com/NewEraCracker/LOIC/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion
Check the wiki: https://github.com/NewEraCracker/LOIC/wiki
Check the releases: https://github.com/NewEraCracker/LOIC/releases

As a future reminder. Any further timewasting activity from you, will get you blocked!
