### ISSUE TITLE
Delay network connection, remove profanities.

### ISSUE THREAD

**Issue by aristosv** [NewEraCracker/LOIC#32]
If for some reason LOIC does not detect an internet connection when starting, it pops up an image saying that I screwed up. This is wrong. It should just retry, until it connects. Windows 7 some times delay network connection.

Also, what is up with all the profanities? First time in my life I see a program using the word fuck so many times. Is there a reason for that? I like to believe that the creator of this program is not a 17 year old.

**Comment by NewEraCracker** [comment]
Old issue. Closing this
