### ISSUE TITLE
Compiling v1.1.1.19 gives some warings in Mono

### ISSUE THREAD

**Issue by Razican** [NewEraCracker/LOIC#36]
I have compiled version 1.1.1.19 in mono, and I get 17 warnings. My system:

Windows 7 64 bits
Mono 2.8.2
MonoDevelop 2.4.2.1

Warning: Assembly 'log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821, processorArchitecture=MSIL' not found. Make sure that the assembly exists in disk. If the reference is required to build the project you may get compilation errors. (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\Channel.cs(88,88): Warning CS0618: 'System.Collections.CaseInsensitiveHashCodeProvider' is obsoleted: 'Please use StringComparer instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\Channel.cs(70,70): Warning CS0618: 'System.Collections.Hashtable.Hashtable(System.Collections.IHashCodeProvider, System.Collections.IComparer)' is obsoleted: 'Please use Hashtable(IEqualityComparer) instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\Channel.cs(88,88): Warning CS0618: 'System.Collections.CaseInsensitiveHashCodeProvider' iis obsoleted: 'Please use StringComparer instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\Channel.cs(70,70): Warning CS0618: 'System.Collections.Hashtable.Hashtable(System.Collections.IHashCodeProvider, System.Collections.IComparer)' is obsoleted: 'Please use Hashtable(IEqualityComparer) instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\Channel.cs(70,70): Warning CS0618: 'System.Collections.Hashtable.Hashtable(System.Collections.IHashCodeProvider, System.Collections.IComparer)' is obsoleted: 'Please use Hashtable(IEqualityComparer) instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Connection\IrcConnection.cs(43,43): Warning CS0618: 'System.Net.Dns.Resolve(string)' is obsoleted: 'Resolve is obsoleted for this type, please use GetHostEntry instead. http://go.microsoft.com/fwlink/?linkid=14202' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Connection\IrcConnection.cs(23,23): Warning CS0168: The variable 'e' is declared but not used (CS0168) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Connection\IrcConnection.cs(23,23): Warning CS0168: The variable 'e' is declared but not used (CS0168) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\IrcClient.cs(102,102): Warning CS0618: 'System.Collections.CaseInsensitiveHashCodeProvider' is obsoleted: 'Please use StringComparer instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\IrcClient.cs(84,84): Warning CS0618: 'System.Collections.Hashtable.Hashtable(System.Collections.IHashCodeProvider, System.Collections.IComparer)' is obsoleted: 'Please use Hashtable(IEqualityComparer) instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\IrcClient.cs(102,102): Warning CS0618: 'System.Collections.CaseInsensitiveHashCodeProvider' is obsoleted: 'Please use StringComparer instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\IrcClient.cs(84,84): Warning CS0618: 'System.Collections.Hashtable.Hashtable(System.Collections.IHashCodeProvider, System.Collections.IComparer)' is obsoleted: 'Please use Hashtable(IEqualityComparer) instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\NonRfcChannel.cs(79,79): Warning CS0618: 'System.Collections.CaseInsensitiveHashCodeProvider' is obsoleted: 'Please use StringComparer instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\NonRfcChannel.cs(61,61): Warning CS0618: 'System.Collections.Hashtable.Hashtable(System.Collections.IHashCodeProvider, System.Collections.IComparer)' is obsoleted: 'Please use Hashtable(IEqualityComparer) instead.' (CS0618) (IRC)
NewEraCracker-LOIC-ec189ab\IRC\Client\IrcClient.cs(34,34): Warning CS0649: The field 'Meebey.SmartIrc4net.IrcClient._PassiveChannelSyncing' is never asigned and its value will always be default false (CS0649) (IRC)

**Comment by NewEraCracker** [comment]
Closing this issue. I may consider merging a Pull-Request that deals with this when submitted.
