### ISSUE TITLE
SSL/I2P support for IRC connections

### ISSUE THREAD

**Issue by antonizoon** [NewEraCracker/LOIC#40]
I'm thinking that it would be useful for the LOIC to have integrated SSL support, so that outsiders are less likely to be able to spy on users.

This is especially the case in France, as they are going to try and cut off internet access to "network security auditors". It is going to be more important to at least make it impractical for ISPs to monitor usage. Compared to an "out in the open" connection, a feature for SSL connections will keep these efforts in check.

The port for SSL is 6697 for AnonOps.

Another possibility is a connection to an IRC in I2P. I2P makes it much more difficult to discover the location of a server, making takedowns impractical. 

I2P automatically encrypts all connections with garlic routing, obscuring the user from the server and spying nodes, keeping them safe even if the server was raided.

We need to do some research on these things. Any comments?

**Comment by NewEraCracker** [comment]
Closing this issue as I2P support won't be implemented and a new separate ticket for SSL support has been created.
