### ISSUE TITLE
HTTPS method

### ISSUE THREAD

**Issue by MostH8** [NewEraCracker/LOIC#62]
I was looking at the http request if it were sent to port 443 and the request were shown as unencrypted
so i was assuming since a lot of sites are getting SSL on their server then adding HTTPS would be a great idea.

I was also thinking maybe you should add like a proxy settings for the HTTP methods
that would be cool.

**Comment by Lucario2** [comment]
You should add the proxy feature. It'll make ur program more popular and have more vast options.

**Comment by laz2727** [comment]
Proxy? For loic? That's like trying to shoot an rpg-7 through a keyhole.

**Comment by MostH8** [comment]
Exactly LOL ^

**Comment by MostH8** [comment]
A proxy feature for the HTTP/HTTPS method is a great idea but adding a proxy feature for LOIC in general is like shooting an rpg-7 through a keyhole.

**Comment by NewEraCracker** [comment]
I wonder... As possible workaround, what about tunelling the requests through stunnel? I bet it might consume a lot of CPU but it's a possibility.
