### ISSUE TITLE
Poject file not found

### ISSUE THREAD

**Issue by rawstring** [NewEraCracker/LOIC#72]
I get this error when installing loic (./loic.sh install)

> /usr/bin/git
> Cloning into 'LOIC'...
> warning: redirecting to https://github.com/NewEraCracker/LOIC.git/
> remote: Counting objects: 1550, done.
> remote: Total 1550 (delta 0), reused 0 (delta 0), pack-reused 1550
> Receiving objects: 100% (1550/1550), 4.23 MiB | 280.00 KiB/s, done.
> Resolving deltas: 100% (1000/1000), done.
> MonoDevelop Build Tool
> Project file not found.

Any ideas what's wrong ? It used to work fine.

**Comment by rawstring** [comment]
I was using the old one now. But the new one also gives me errors when installing.
Check output here:
[http://rawstring.com/paste/?5f0c3b75715d1fa7#PX+jQ0TcyQivLuhcmchomdIbt9GW1te+Bhxz2u8MR8U=](url)

**Comment by NewEraCracker** [comment]
Let me know how the script goes with the recent change.

**Comment by rawstring** [comment]
Tried with new changes, only change I see is the text comes in colors now.
[http://rawstring.com/paste/?682c59adbdb3055c#wrw+wUwkZL5P8lWd26RbH2lKidOPQfZa9cWEWFTxUD0=](url)

**Comment by NewEraCracker** [comment]
Maybe doing the following could help:
https://github.com/NewEraCracker/LOIC/blob/master/loic.sh
Edit line 77 from:
```cd src; xbuild /p:TargetFrameworkVersion="v4.0"```
To:
```cd src; xbuild /p:TargetFrameworkVersion="v4.5"```

Reference:
https://github.com/hirschmann/nbfc/issues/86

**Comment by rawstring** [comment]
Now it's output looks like this:
[http://rawstring.com/paste/?85f42c350c481411#v6b/vOWNFab+HJGr+PpyPGyDwMJBbttLJN05brtFIO4=](url)

**Comment by NewEraCracker** [comment]
Better. Should have been built.

I'll keep this bug open until I figure a solution to detect available .net versions on the linux distro.

Error log snippet for future reference:
```
CSC: error CS0518: The predefined type `System.Object' is not defined or imported
CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported
CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported
CSC: error CS0518: The predefined type `System.Int32' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt32' is not defined or imported
CSC: error CS0518: The predefined type `System.Int64' is not defined or imported
CSC: error CS0518: The predefined type `System.UInt64' is not defined or imported
(...)
```

**Comment by rawstring** [comment]
Maybe it's due to new kernel update ?

**Comment by NewEraCracker** [comment]
I doubt it. It's more an issue with some new version of mono or package configuration breaking backwards compatibility with projects for older versions.

**Comment by NewEraCracker** [comment]
Fixed.
