### ISSUE TITLE
Install LOIC error

### ISSUE THREAD

**Issue by romeotaja** [NewEraCracker/LOIC#73]
Cloning into 'LOIC'...
warning: redirecting to https://github.com/NewEraCracker/LOIC.git/
remote: Counting objects: 1556, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1556 (delta 2), reused 6 (delta 2), pack-reused 1550
Receiving objects: 100% (1556/1556), 4.23 MiB | 2.00 MiB/s, done.
Resolving deltas: 100% (1002/1002), done.
./loic.sh: line 75: mdtool: command not found

**Comment by NewEraCracker** [comment]
Use this script:
https://github.com/NewEraCracker/LOIC/blob/master/loic.sh

**Comment by NewEraCracker** [comment]
Closing issue due to lack of more information.

**Comment by NuKESec** [comment]
don't install this guys. there's no legitimate LOIC anymore. this is a rat

**Comment by NuKESec** [comment]
LOIC is shit now anyway. it uses old methods that can be easily avoided

**Comment by scorp1on-s** [comment]
You have to install mdtool! I cant, pls tell me if you find a way.

**Comment by NewEraCracker** [comment]
Read the instructions: https://github.com/NewEraCracker/LOIC/blob/master/loic-net4.5.sh
