### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by rawstring** [NewEraCracker/LOIC#74]
Installation fails !!
Log report :

https://rawstring.com/paste/?245bf44c03dc79a8#hYBAn2UNzNP1a4VL7Vn5JCFvsBNFADvA4Pk6xvt9boA=

**Comment by JamesMatchett** [comment]
Are you using the install script?

**Comment by NewEraCracker** [comment]
It is not actually new.
https://github.com/NewEraCracker/LOIC/issues/72#issuecomment-383330364

It's Mono, they like to break backward compatiblity!

**Comment by NewEraCracker** [comment]
Fixed!

**Comment by Voightr** [comment]
Still not fixed
