### ISSUE TITLE
The following packages have unmet dependencies:

### ISSUE THREAD

**Issue by pruthvi210** [NewEraCracker/LOIC#75]
The following packages have unmet dependencies:
 liblog4net-cil-dev : Depends: liblog4net1.2-cil (= 1.2.10+dfsg-7) but it is not going to be installed
 mono-devel : Depends: libmono-system-drawing4.0-cil (>= 3.0.6) but it is not going to be installed
              Depends: libmono-system-runtime4.0-cil (>= 2.10.1) but it is not going to be installed
              Depends: libmono-system-servicemodel4.0a-cil (>= 3.2.3) but it is not going to be installed
              Depends: libmono-system-web-services4.0-cil (>= 1.0) but it is not going to be installed
              Depends: libmono-cil-dev (= 5.12.0.226-0xamarin3+ubuntu1804b1) but it is not going to be installed
              Recommends: msbuild but it is not going to be installed
 monodevelop : Depends: fsharp but it is not going to be installed
               Depends: libglade2.0-cil (>= 2.12.40) but it is not going to be installed
               Depends: libgtk2.0-cil (>= 2.12.40) but it is not going to be installed
               Depends: libmono-microsoft-web-infrastructure1.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-design4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-drawing4.0-cil (>= 3.0.6) but it is not going to be installed
               Depends: libmono-system-runtime4.0-cil (>= 2.10.1) but it is not going to be installed
               Depends: libmono-system-servicemodel4.0a-cil (>= 3.2.3) but it is not going to be installed
               Depends: libmono-system-web-extensions4.0-cil (>= 2.10.3) but it is not going to be installed
               Depends: libmono-system-web-services4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-web4.0-cil (>= 2.10.3) but it is not going to be installed
               Depends: libmono-system-windows-forms4.0-cil (>= 1.0) but it is not going to be installed
               Depends: msbuild but it is not going to be installed
               Recommends: libgtk2.0-cil-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by NewEraCracker** [comment]
Ask in Ubuntu forums how to fix this.

It is amazing how backwards compatibility is always broken when major releases happen.

**Comment by nbctcp** [comment]
compiled without problem with Kali 04/18

**Comment by NewEraCracker** [comment]
Related to #79 ?
