### ISSUE TITLE
hello can publish console versions

### ISSUE THREAD

**Issue by zhmmmm** [NewEraCracker/LOIC#78]
hello can publish console versions

**Comment by JamesMatchett** [comment]
Hey, just wanting to clarify this issue. Are we looking to put together a console version of LOIC? 

Apologies if this is a dumb question -James

**Comment by zhmmmm** [comment]
sorry

**Comment by NewEraCracker** [comment]
Feel free to contribute @JamesMatchett

**Comment by IlkaySolotov** [comment]
Since im bored asf, I'll do.
