### ISSUE TITLE
HackTool:Win32?

### ISSUE THREAD

**Issue by ForkBombWindows** [NewEraCracker/LOIC#80]
My antivirus found the Oylecann virus associated with the Fynloski backdoor Trojan and I don't want to give anyone access to my PC. So I should use a different penetration test program. I just wanted to report this problem.

**Comment by NewEraCracker** [comment]
This an "Hack Tool" if you use it right. However it is a get v&ed tool if you use it wrong.

If you trust the Antivirus is right, then you shouldn't use this tool anyway.
