### ISSUE TITLE
Mono method is outdated

### ISSUE THREAD

**Issue by TNTBOMBOM** [NewEraCracker/LOIC#82]
Im trying to install it using mono method but `monodevelop` package doesnt exist anymore thus hindering the installation of it.

**Comment by NewEraCracker** [comment]
Read the comment of the loic.sh and loic-net4.5.sh
```
# Before using you must install monodevelop from:
# https://www.monodevelop.com/download/#fndtn-download-lin
```
You need to install their package first from their own repository since some distributions no longer include it.

**Comment by NewEraCracker** [comment]
I have added this info to the article in the wiki: https://github.com/NewEraCracker/LOIC/wiki/How-to-run-LOIC-using-Mono

**Comment by TNTBOMBOM** [comment]
alright great!

closing as resolved.
