### ISSUE TITLE
Wrong/old instructions of wine installation

### ISSUE THREAD

**Issue by TNTBOMBOM** [NewEraCracker/LOIC#83]
Wine instructions doesnt work directly as it mentioned here it needs some improvements: 

There is Wine64 and Wine32 , `apt install wine` it will install wine64 because Debian and most distros deprecating/not using by default i386 architecture, so user need to specify the wine version.

Better refer the user to install wine on debian from the official website of winehq: 

https://wiki.winehq.org/Debian

(why do we need 32bit? because loic architecture is 32bit)

**Comment by NewEraCracker** [comment]
I have edited the wiki entry to add your comment:
https://github.com/NewEraCracker/LOIC/wiki/How-to-run-LOIC-using-Wine

**Comment by TNTBOMBOM** [comment]
Ok awesome! 

Thx :)

Closing as resolved.
