### ISSUE TITLE
Problems building LOIC with mdtool build file not found

### ISSUE THREAD

**Issue by r63b** [NewEraCracker/LOIC#89]
I'm working on an Ubuntu server and am trying to build LOIC as instructed in the support documentation. When I write mdtool build I get the error project file not found. I'm in the folder containing LOIC when I run the command.
![Screenshot 2020-05-06 at 21 23 38](https://user-images.githubusercontent.com/4274904/81224609-e0c97700-8fdf-11ea-92d8-36262ff3efe6.png)

**Comment by NewEraCracker** [comment]
The project file in inside the src folder.

**Comment by NewEraCracker** [comment]
Alternatively you could use loic.sh or loic-net4.5.sh script (depends on the .net version available on your system)
