### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by PrismaticEwe** [NewEraCracker/LOIC#91]
I tested it out on myself, and put my public IP in the IP section and put threads to 20 and tested it and I lost my wifi a few moments later. Then I tested it again and its not working

**Comment by PrismaticEwe** [comment]
It says 20 connected in the bottom as well but my wifi is fine and I increased threads to 99 still doesnt work I also ran it as admin

**Comment by SplittyDev** [comment]
What do you actually think should happen when putting your own public IP into the target field?
You're practically trying to flood your own ISP which will do absolutely nothing.
Also, using a massive amount of threads surely doesn't help.
