### ISSUE TITLE
It disconnects my wifi when using it

### ISSUE THREAD

**Issue by thecomputermaster** [NewEraCracker/LOIC#93]
Hi,

So LOIC disconnects my wifi when I am trying to use the app. When I click Imma chargin mah laser it starts then my wifi disconnects . I've tried this on two different routers now. Is this a new router security issue? Thanks.

**Comment by uyeet** [comment]
The problem maybe your wifi, I used UDP unicorn when I used large amounts of packets/treads and It would disconnect me.
